### ISSUE TITLE
fix(experiments): run_arms.py constructs GatherDeps(is_main_session=…) — removed kwarg (pre-existing)

### ISSUE THREAD

**Issue by beetroot-salad** [beetroot-salad/cyber-response-agent#501]
Surfaced by the PR #490 code review's cross-file trace. **Pre-existing** (not introduced by #490) and under `experiments/` (off the CI-collected path), filed separately for visibility.

### Where
`experiments/gather-verifiable-code-289/run_arms.py` — a `GatherDeps(...)` construction.

### Bug
The call passes `is_main_session=False`, which is no longer a field of `GatherDeps`/`RunDeps` (current fields: `run_dir, defender_dir, run_id, salt, policy, lead_id, query_id`). Importing/executing the file raises `TypeError: __init__() got an unexpected keyword argument 'is_main_session'`. The same file also calls the old positional `tools._gather_prompt(deps, lead_id, system, …)` shape. `is_main_session` was dropped in an earlier refactor; this experiment script wasn't updated and isn't exercised by CI.

### Suggested fix
Update the script to the current `GatherDeps`/`_gather_prompt` signatures, or delete/archive the experiment if it's no longer needed.
